### ISSUE TITLE
Map textures missing

### ISSUE THREAD

**Issue by ahaasler** [SonofUgly/VCS-Texture-Pack#2]
Hi,

thanks for your work on this texture pack but I noticed that the map images are missing even though they are referenced on the textures.ini file.

Is that an error?

**Comment by SonofUgly** [comment]
Not an error, no.

I used textures.ini to catalog and organize the textures I had intended to redo. This project was never finish though so there's many textures I never got around to.

**Comment by ahaasler** [comment]
Is there anything I can do to help? There's a AI upscaled pack that we could use, but I'm not aware of the LICENSE on those files.

**Comment by SonofUgly** [comment]
Doubt I'll get back to this, but if you want to fork this or start your own project you're free to use any or all files I've made here if you want.
